### ISSUE TITLE
pip3 should be installed 

### ISSUE THREAD

**Issue by lioramilbaum** [code-collab-comm/baboon#34] opened 2020-02-16 09:56 UTC
To run a python application, it is required to have pip3 installed. Add pip3 installation to the bootstrap script, such that when spinning an environment pip3 is present.

**Comment by IlanZuckerman** [comment] 2020-02-18 08:47
This is already taken care of as a part of issue "[documentation] Deploy virtualenvwrapper on host #38".
So this issue can be removed @lioramilbaum

**Comment by lioramilbaum** [comment] 2020-02-18 12:06
@IlanZuckerman Not sure how this is related. Please see the comment I have added in #38

**Comment by IlanZuckerman** [comment] 2020-02-19 10:01
This is a duplicate of #36

**Closed** 2020-02-19 10:35 UTC
